### ISSUE TITLE
In My Library, replace search action with refresh (to check for latest chapters)

### ISSUE THREAD

**Issue by williamxu** [williamxu/MangoReader#11]

**Comment by ckmah** [comment]
library isn't saved between app instances

**Comment by akrolsmir** [comment]
Are we not enabling a search within your library? My batoto library has like 100+ manga in it...

**Comment by williamxu** [comment]
^power user right here

Sure, we'll probably have search.

**Comment by ckmah** [comment]
i'll get to this if i have time, shouldn't be too hard since all the pieces are there

**Comment by akrolsmir** [comment]
Hm, I'm still not sure I understand the scope or purpose of this feature. Is it like: User hits refresh button -> immediately trigger a new chapter check over their library, and tell them if any of their manga has had an update that they have not read?

**Comment by williamxu** [comment]
Hm.I'm thinking it might not be necessary. Do you have a case for taking it
out? Maybe the user opts out from automatic checking, but then it could
just check for new updates when opening the app.... Thoughts?
