### ISSUE TITLE
change no image placeholder image

### ISSUE THREAD

**Issue by williamxu** [williamxu/MangoReader#39]

**Comment by ckmah** [comment]
wait till rebranding to fix

**Comment by ckmah** [comment]
probably b/c of PhotoView library thing @williamxu what have you done

**Comment by ckmah** [comment]
seems like we want dango daikazoku bouncing dango
reference: https://www.youtube.com/watch?v=qvzCmV3_12c (first ~4 seconds)

**Comment by williamxu** [comment]
Is this still an issue? Can we consider this part of the rebranding issue

**Comment by akrolsmir** [comment]
Closed by #88.
