### ISSUE TITLE
reverse page swiping (make it left to right) and a togglable option in settings

### ISSUE THREAD

**Issue by williamxu** [williamxu/MangoReader#40]

**Comment by akrolsmir** [comment]
Hm, I'm not sure that's the best solution to the problem of "our users are used to swiping left to right". Instead, maybe we could show a splash screen/tutorial at the start of each chapter, showing the chapter number and title, in addition to subtle instructions (i.e. where to press for next/previous/show menu, etc.)

**Comment by ckmah** [comment]
so include tutorial/tooltip thing + have the option in global settings and mangaviewactivity?

**Comment by akrolsmir** [comment]
Continue in #43
