### ISSUE TITLE
mangaview image caching

### ISSUE THREAD

**Issue by ckmah** [williamxu/MangoReader#50]
first fragment shown sometimes displays another page; possibly caching problem

**Comment by akrolsmir** [comment]
Yeah, I get this issue sometimes when I get to the end of one chapter, and then try to go to the next chapter by tapping on the left side. Not consistently reproduceable though...

**Comment by akrolsmir** [comment]
... Think this was literally a one line bug: ![](http://i.imgur.com/KytsXcw.png)

**Comment by williamxu** [comment]
amazing
