### ISSUE TITLE
New chapter notification

### ISSUE THREAD

**Issue by akrolsmir** [williamxu/MangoReader#66]

**Comment by akrolsmir** [comment]
WIP on 'austin' branch. Right now, it pulls the last updates in 24 hours, and then matches against the library, and sends a notification for all chapters.

Considerations/TODO:
- [x] Figure out background cycling details
- [x] Skip cache, always use newest data
- [x] Include updated chapter number in notification
- [x] Allow user to disable
- [x] Don't alert if user already read latest (i.e. Naruto updates from ch. 700 to 701, and user already read 701)
- [ ] Check for updates on wifi only

Probably not implementing:
- [ ] Allow user setting for update frequency?
- [ ] Play with notification copy text? e.g. "3 new chapters available", "
- [ ] What happens if multiple updates happen at once?
- [ ] Don't alert if user isn't caught up (i.e. Naruto updates from ch. 700 to 701, but user is on 650)

**Comment by ckmah** [comment]
#81 implements vast majority of these

**Comment by ckmah** [comment]
since the bulk of new chapter notification functionality is already implemented as stated above, moving unimplemented features to new issue
