### ISSUE TITLE
rebranding

### ISSUE THREAD

**Issue by ckmah** [williamxu/MangoReader#73]
assets needed:
- [x] logo
- [ ] manga art placeholder (stylized "..."?)
- [x] notification logo silhouette thingy @akrolsmir
- [x] color scheme

**Comment by ckmah** [comment]
bring back gray bars placeholder for manga item

**Comment by ckmah** [comment]
gray placeholder for browse load screen

**Comment by mragsac** [comment]
- [ ] color scheme : same as dev color scheme ( amber 500 )
- [ ] created empty library placeholder
- [ ] logo : in finalization stage
- [ ] manga art placeholder: same as dev icon ( missing image placeholder )

**Comment by williamxu** [comment]
- [x] Change name of app to DangoReader
- [x] Change icon on notification to a dango icon (white with transparent background)
- [x] Change the placeholder for a manga detail page? Right now it's just grey bars and grey box
- [x] Change no image placeholders? This would be the same for all images, like library card images, browse card images, detail page image, and viewpager images. My friends suggest using the dango theme
