### ISSUE TITLE
Sometimes "Browse" title shown over My Library page

### ISSUE THREAD

**Issue by akrolsmir** [williamxu/MangoReader#90]
Usually when you return to the app after it's been there a while. Could be an onSaveInstanceState thing.

Unfortunately hard to replicate.

**Comment by williamxu** [comment]
To replicate, open a bunch of other apps before returning to the app. Unfortunately, almost every activity crashes when doing this.

**Comment by williamxu** [comment]
Crashes caused because Paper.init() not called
